cc_binary(
    name = "fasttext_example",
    srcs = ["fasttext_example.cc",],
    deps = [
        "@com_github_facebookresearch_fasttext//:fasttext",
    ]
)

cc_binary(
    name = "cjk_tokenizer_example",
    srcs = ["cjk_tokenizer_example.cc",],
    deps = [
        "@com_github_liuzl_cjk_tokenizer//:cjk_tokenizer",
    ],
)
